### ISSUE TITLE
После перезагрузки компьютера расширение перестаёт работать

### ISSUE THREAD

**Issue by megapro17** [qrlk/videochatru-extension#10]
Если установить расширение, то оно работает нормально, до первой перезагрузки, после этого IP не показывается, как и другие опции, например по скрытию логотипа

**Comment by qrlk** [comment]
Я обновил расширение до нового манифеста, может это поможет.

**Comment by megapro17** [comment]
Нет, ничего не изменилось. Вот как это выглядит: галочки отмечены, но никакого эффекта нет. Так же не показывается местоположение
![image](https://user-images.githubusercontent.com/16743370/170839433-29ddc3e7-75ba-41ab-8b61-cb309bc9edc3.png)

**Comment by qrlk** [comment]
> можно пожалуйста решить эту проблему? каждый раз переустанавливать расширение напрягает

если открывать https://videochatru.com/embed, например, нажав на иконку расширения, то будет работать?

**Comment by megapro17** [comment]
Нет, всё равно не работало, я пробовал

**Comment by qrlk** [comment]
> Нет, всё равно не работало, я пробовал

Тогда нужен скрин консоли (F12->консоль, промотать выше), должна быть какая-то ошибка красным цветом...
Я не могу решить проблему, если не могу её воспроизвести и не понимаю её корней.

**Comment by qrlk** [comment]
Пожалуйста, откройте issue снова, когда у вас появится настроение сообщить необходимую для поиска проблемы информацию.

Больше никто с такой проблемой не обращался.
