### ISSUE TITLE
Videochatru.com keeps freezing with websocket hacks enabled

### ISSUE THREAD

**Issue by Loemnk** [qrlk/videochatru-extension#11]
Hey there, been using this for the past 3 weeks on and off and it was working fine.

But recently whenever I try to use this, the whole Website (videochatru.com) keeps freezing after about 4-5 minutes.
and I have to restart it in a new tab.
This is only happening when you have websocket hacks enabled!
Without it, it works fine.

Cheers and thank you for the software

**Comment by qrlk** [comment]
👋

I was unable to reproduce the problem. I was in a video chat with ws hacks enabled for 10 minutes and found no freezing issues.

Perhaps more information from you could help me to better understand the problem.

* What does your ws hacks settings section look like (which tweaks are enabled)?
* Did you log in to the system through VK/Facebook?
* Which web browser do you use?
* Does the problem persist if all other browser extensions are disabled?

**Comment by qrlk** [comment]
nvm, I walked away from the computer for a few minutes and when I returned I found a hung tab. The chat was paused.

I'll see what can be done.

**Comment by qrlk** [comment]
I think I fixed it, you need to wait for Google to approve the new version so you can update and confirm that everything works now.

**Comment by qrlk** [comment]
no fix didn't work

Use an older version of the browser until the issue is resolved. Not sure if it's a bug in chrome or my fault.

https://portapps.io/app/brave-portable/

**Comment by qrlk** [comment]
please test if v1.1.3 worked

**Comment by Loemnk** [comment]
I've been testing this for a little bit over an hour and it seems to be fixed! No hanging or freezing.

Also, just for the sake of testing, I've enabled every single Websocket Hack.
![websocket enabled](https://user-images.githubusercontent.com/38075173/182843454-57ccc8b4-5267-4c6c-bbaf-cf20fcf2cb82.png)

Thank your for your time and effort!

**Comment by qrlk** [comment]
cool

something has changed, now the system periodically requests some 'GetFaceData' information. I just disabled this command but didn't go deep and can't guarantee something won't break in the future because of it.

but thanks for reporting the problem, feedback is something the project is missing
