### ISSUE TITLE
Feature Request: Option to search for multiple regions and cities

### ISSUE THREAD

**Issue by Loemnk** [qrlk/videochatru-extension#12]
Hey, it's me again,

but this time I just wanted to ask if this would be possible to implement.
Unless I'm doing something wrong, right now you can only search for a specific region and/or city.

Would it be possible to set up whatever x amount of cities and regions you wanted to? Or maybe something like a radius and get 
matched with people from within that radius. Would be a cool feature.

Again, thanks for taking the time.

Cheers

**Comment by qrlk** [comment]
yes it's possible, just need to change https://github.com/qrlk/videochatru-extension/blob/fa17b09c0d118fd727ceb42719a407840d6105ff/src/content.js#L281 to something like 
```javascript
 if (!settings.targetCity.includes(json.city)) { 
```
and specify the string with target cities in a format like 'City1, City2, City3' and it will work the way you want.

same goes for a targetRegion thing

radius is also possible but I think it would complicate things, why need radius if you can filter by region? plus ip geolocation is not really accurate...

anyway, I will not release this update right away, I need to focus on another project in the coming months and if I go back to this extension it will be an endless cycle of small edits

**Comment by qrlk** [comment]
![image](https://user-images.githubusercontent.com/40423143/187788065-65348cd6-f686-4ba4-9871-3f1ba260ff6b.png)
