### ISSUE TITLE
Ability to use mirror mode without camera/microphone

### ISSUE THREAD

**Issue by qrlk** [qrlk/videochatru-extension#3]
Mirror mode is useful when the user's PC does not have a physical camera.  
Users must install some sort of virtual camera and change its name in the registry to use mirror mode.

Need to find a way to allow using mirror mode without a physical camera/mic by providing non-existent cameras/mics and replacing its streams with fake mirror ones.

**Comment by alexey9090** [comment]
за что меня забанили?

**Comment by qrlk** [comment]
mirror mode was discontinued so no need for this thing anymore
