### ISSUE TITLE
Structure settings secture

### ISSUE THREAD

**Issue by qrlk** [qrlk/videochatru-extension#4]
There are a lot of settings that most users probably don't even touch.

It would be better if each setting will belong to some category and contain a help (?) section with a popup on what it does.

**Comment by qrlk** [comment]
![image](https://user-images.githubusercontent.com/40423143/147430681-497fd222-9fd1-485a-b273-9f2937b36e0b.png) -> ![image](https://user-images.githubusercontent.com/40423143/147430643-0c04edd3-221f-4669-a065-1aff3b86193f.png)
done

**Comment by Rainyale** [comment]
Skip men

**Comment by Rainyale** [comment]
Skip men
