### ISSUE TITLE
Blur NSFW content (YouTube streamers)

### ISSUE THREAD

**Issue by qrlk** [qrlk/videochatru-extension#5]
There are some NSFW detection experiments on [prikol](https://github.com/qrlk/videochatru-extension/tree/prikol) using nsfwjs.

I streamed mirrored Chatruletka on YouTube for 24 hours, encountered some NSFW interlocutors who were blurred, and YouTube was ok with it.  
But because of the poor image quality, there are a lot of false positives.

I think this feature will be helpful to YouTube streamers, which will ultimately have a positive impact on the distribution of the extension.

The extension needs better implementation of this functionality. 
Maybe replace remote-video with canvas and render image there only when nsfwjs checked it? Then, the original video could also be shown in PiP.
What else would people want? Temporarily switching off the function until the current conversation ended? Flexible configuration of when to blur? 

I should find some time to develop this direction.

**Comment by qrlk** [comment]
done

**Comment by Alexrubakov** [comment]
Приходят много ложных банов.  Надо исправить . Это дискредитирует чатрулетку
