### ISSUE TITLE
websocket hacks

### ISSUE THREAD

**Issue by qrlk** [qrlk/videochatru-extension#6]
There are some ws hacks in the [prikol](https://github.com/qrlk/videochatru-extension/tree/prikol) branch.

This allows doing cool staff like substitution of reportPic and detecting if interlocutor skipped us.
It also allows to fast skip interlocutor if he's not from the country we are looking to find interlocutors from.

I have to evaluate what of this should get into the main in order to preserve the principle of harmlessness.

The dilemma is that despite the substitution of pictures for the report, if the system records many reports on you from different people, you will still get banned. Therefore, such a function can help avoid accidental bans due to a blurred picture, but nasty pests still will not hide from the ban.

I saw a guy in Chatruletka who hacked it so that my report button didn't work at all, and he was sitting with a stick out and trolling people. I think he had some custom client.

It would be fun to implement something like this (prohibit the interlocutor from pressing the report button), but I don't have the skills to do it.
I spent 10 hours finding vulnerabilities in the obfuscated code and eventually found only the possibility of image substitution and not a complete ban on using the report button from a person.

**Comment by qrlk** [comment]
![image](https://user-images.githubusercontent.com/40423143/147430729-cf0ee568-7512-4ca2-a1cd-7e1827315a38.png)

**Comment by DiegoMax** [comment]
Are these options gone ?
